# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displays', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='color_code',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
