# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displays', '0002_information_color_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='/logos/images/')),
                ('banner', models.ImageField(upload_to='/brand/images/')),
            ],
        ),
    ]
