# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displays', '0003_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='banner',
            field=models.ImageField(upload_to='brand/images/'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(upload_to='logos/images/'),
        ),
        migrations.AlterField(
            model_name='information',
            name='image',
            field=models.ImageField(blank=True, upload_to='information/images/'),
        ),
    ]
