# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displays', '0006_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='mkting',
            field=models.ImageField(blank=True, upload_to='mkting/image/'),
        ),
    ]
