# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reportingIndividual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Position_Title', models.CharField(blank=True, max_length=100, null=True)),
                ('Phone_no', models.CharField(blank=True, max_length=100, null=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('report_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.IncidentReport')),
            ],
        ),
    ]
