# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-27 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_auto_20160530_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='station',
            field=models.CharField(choices=[('Harare', 'Harare'), ('Vic Falls', 'Vic Falls'), ('Bulawayo', 'Bulawayo'), ('Kariba', 'Kariba')], default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='upload_evidence',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
