# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-15 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_auto_20180227_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='station',
            field=models.CharField(choices=[('Harare', 'Harare'), ('Vic Falls', 'Vic Falls'), ('Bulawayo', 'Bulawayo'), ('Kariba', 'Kariba'), ('Other', 'Other')], default=0, max_length=20),
        ),
    ]
