# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-15 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0005_auto_20180315_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='other_station',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
