# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-28 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0006_incidentreport_other_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, default='WUd3WH3f9UD', max_length=11, null=True, unique=True)),
                ('report_status', models.CharField(max_length=20, null=True)),
                ('report_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.IncidentReport')),
            ],
        ),
    ]
