# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-01 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0007_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='additional_details',
            field=models.TextField(default=1, max_length=3000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tracking',
            name='tracking_number',
            field=models.CharField(blank=True, default='4AsWiu', max_length=11, null=True, unique=True),
        ),
    ]
