# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-17 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0008_auto_20180401_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='additional_details',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='report_status',
            field=models.CharField(choices=[('Evaluation', 'Evaluation'), ('Investigation', 'Investigation'), ('Disciplinary ', 'Disciplinary'), ('Insufficient', 'Insufficient Evidence'), ('Closure', 'Closure')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='tracking_number',
            field=models.CharField(blank=True, default='8S3p58C', max_length=11, null=True, unique=True),
        ),
    ]
