# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-10 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0009_auto_20180417_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentreport',
            name='specific_location',
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='nature_of_report',
            field=models.CharField(choices=[('Smuggling', 'Smuggling'), ('Fraud', 'Fraud'), ('Extortion', 'Extortion'), ('Bribery', 'Bribery'), ('Corruption', 'Corruption'), ('Misappropriation', 'Misappropriation'), ('Other', 'Other'), ('Nepotism', 'Nepotism'), ('Procurement Fraud', 'Procurement Fraud'), ('Racism', 'Racism'), ('Theft', 'Theft'), ('Sexual Harassment', 'Sexual Harassment'), ('Criminal', 'Criminal'), ('Unethical', 'Unethical'), ('Other', 'Other')], default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='station',
            field=models.CharField(choices=[('Harare', 'Harare'), ('Victoria Falls', 'Victoria Falls'), ('Bulawayo', 'Bulawayo'), ('Kariba', 'Kariba'), ('Other', 'Other')], default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='upload_evidence',
            field=models.FileField(blank=True, null=True, upload_to='tipoff_media/'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='report_status',
            field=models.CharField(choices=[('Evaluation', 'Evaluation'), ('Investigation', 'Investigation'), ('Disciplinary ', 'Disciplinary'), ('Insufficient', 'Insufficient Evidence'), ('Closed', 'Closed')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='tracking_number',
            field=models.CharField(blank=True, default='16E9m', max_length=11, null=True, unique=True),
        ),
    ]
